### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by Usagib**

### CODE REVIEW

**Comment by Usagib** [comment]
Hi team! already finished this project (uff)
on the lookout for code review and changes
Happy Coding!

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @Usagib :wave: 

You have really done well so far, but there are a few places that need fixing.

- [x] The **Sign in and Subscribe links** on the navbar should actually be links. Please make them **links**
- [x] You are missing [vieport metatag](https://getbootstrap.com/docs/4.3/getting-started/introduction/#responsive-meta-tag)

**Kindly submit another code review request after fixing those issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by Usagib** [comment]
Hey @ebukaume  thank you for the review!
i'va applied the changes and sent another code review.
happy coding and great job!

**Comment by shshamim63** [comment]
### Changes Required!
Hi @Usagib :wave:
All I can say, impressive work :sunglasses:. Maintained the flow of the project as required. Only two things i will mention in this project.
Please follow the instruction below to make this project complete.:point_down:
___
#### Mandatory Change:
It seems that your webpage is overflowing. Which is rendering a horizontal scrollbar. And it is destroying the initial view of this project.
horizontalbar
:point_right: For sure I also faced this kind of problems. There are several techniques to solve this issue. i follow [this](https://css-tricks.com/findingfixing-unintended-body-overflow/). 
___
#### [Optional change]
---> Actual footer
actualfooter
---> Project footer
projectfooter

Well in this project you have cracked more difficult part than this :fire:. So,, I believe you can cover this change easily :smiley:.

##### Please submit another code review request after fixing those issues. 
## <em>Happy Coding</em> 
 [Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Comment by Usagib** [comment]
Hi team!
Corrected the scrollbar problem using hidden overflows, (because couldn't find the source of the problem) still no content got clipped with the adjustments
and also styled the footer to llok more like the original page
thank you guys happy coding!

**Review by Redvanisation — APPROVED** [review]
### Hello @Usagib 🌟 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
