### PR TITLE
pull-1

### PR DESCRIPTION
**Pull request by Usagib**

### CODE REVIEW

**Comment by Usagib** [comment]
peer to peer code review oct-17 using bootstrap

**Comment by Usagib** [comment]
Hey Usagi! Ur code sucks! XD JK

**Comment by SantiagoGuerra** [comment]
* You can insert the bootstrap link in your project, so you won't have to download it and your server will be faster
* You can use a different css class for fonts

**Comment by Usagib** [comment]
Cierro pull pa que no anden de chismosos XD

**Pull request closed without merging**
